cloudfoundry/bosh-io-releases

index.yml
node_exporter is commonly used as an addon to gather detailed VM metrics
=> Add node_exporter

index.yml
Hi,
We have open sourced our `cf-rabbitmq-multitenant-broker-release` and would like to distributed that on bosh.io, the same way we distribute `cf-rabbitmq-release`.
Cheers
=> Add cf-rabbitmq-multitenant-broker-release

index.yml
Required for `cf-deployment` to be able to use a rootfs release for the `windows2016` stack.
Release repo: https://github.com/cloudfoundry-incubator/windows2016fs-online-release
=> Add windows2016fs-online-release

index.yml
We want to rename the repo from github.com/cloudfoundry/loggregator to github.com/cloudfoundry/loggregator-release.
We are unsure how to get the `worker` to start polling the new URL.
=> Replace loggregator with loggregator-release

index.yml
windows-tools-release is a release for installing miscellaneous packages on a BOSH deployed Windows VM (e.g. ruby, docker, etc.)
=> Add windows-tools-release

index.yml
We would like for bosh.io to pick up `silk-release`, which has been split out from `cf-networking-release`.
Cheers,
Angela
=> Add silk release

index.yml
i've created a minecraft boshrelease to use as a teaching and promotion tool.
it might seem somewhat "frivolous" but i feel that using something "playfull" can really help when trying to promote new technologies and ideas,
the release can work with persistent disks which is cool because it allows me to modify the minecraft world, destroy the deployment, salvage the orphaned disk, attach it to a new deployment, and show people that the little cabin we build is still there.
todo:
modify java startup settings with deployment properties.
=> added minecraft-boshrelease

index.yml
[Project Harbor](https://github.com/vmware/harbor/) is an enterprise-class registry server 
that stores and distributes Docker images. 
Add the following snippet into the bosh deployment manifest file to deploy Project Harbor:
```
releases:
- name: harbor-container-registry
version: 1.5.0
sha1: ded9ed8a5e2efadc3aed26444710d8446483bd59
url: https://storage.googleapis.com/harbor-bosh-releases/harbor-container-registry-1.5.0.tgz
```
=> Add harbor-boshrelease into index.yml

index.yml
kept the original concourse/concourse there to give folks time to transition
not sure if that'll actually keep working, though, since we'll soon replace concourse/concourse with a non-bosh-release repo (though the bosh release will remain in the old commits in the git history)
=> add concourse-bosh-release

index.yml
Only keep nfs-volume-release from cloudfoundry organization.
=> Remove nfs-volume-release from cloudfoundry-incubator

index.yml
VSphere, AWS, OpenStack, Azure, and google graduated to 'active'
projects and move therefore out of incubation.
We keep both locations here for a period of time (incubator as
well as cf org) and will remove the incubator entries with a
subsequent PR.
=> Add CPIs which have moved to cf org

index.yml
This is the rootfs release for 1803 Windows cells. We are moving towards having 1803 cells be the default for CF Windows deployments.
=> Added 1803 release to index.yml

index.yml
The release is so we can deploy Envoy to Windows Diego Cells. Instead of keeping it as a blob in diego-release, we provide a separate release that can be co-located
cc: @natalieparellano
=> Add envoy-release to bosh.io

index.yml
We moved to a different blobstore, releases 1 and 2 are no longer possible to build.
=> Set minimum version of ipsec to 3

index.yml
This bosh release is a pre-req of https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release, and it does not make sense to release the dependent without the dependency, as pointed out in https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release/issues/2
Resolves https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release/issues/2
=> Add cf-rabbitmq-smoke-tests

index.yml
For now this adds support for the 2019 OS (similar to how [this PR](https://github.com/bosh-io/releases/pull/50)
added support for 1803), the plan is to eventually move the 1803 and 2016
rootfs's into this release so we don't have to maintain 3 seperate releases.
[#163988757]
Signed-off-by: Natalie Arellano <narellano@pivotal.io>
=> Added generic online windows rootfs release to index.yml

index.yml
This release contains the new Istio routing tier that the CF Networking program has been working on. It can be deployed alongside the existing Routing Release.
[#164546946]
Please let us know of any concerns.
Regards,
CF Networking
=> Add cloudfoundry/istio-release

index.yml
Hi,
We are maintaining the Eirini bosh release from community @SUSE, would be nice to have it as a release on bosh.io, let me know if anything else is needed.
Thanks
=> Add Eirini bosh release

index.yml
The `bpm-release` repository was recently moved from `cloudfoundry-incubator` to `cloudfoundry`. This change updates the release index to point at the new location.
=> update bpm-release organization

index.yml
pivotal-cf/cf-redis-release has been deprecated and replaced with pivotal-cf/shared-redis-release
=> Move cf-redis-release to shared-redis-release

index.yml
This is deployed in many production CF deployments and is OSS, so it should be available on bosh.io
=> Add the notifications-release to bosh.io

index.yml
event-log-release is OSS and common in production deployments
=> Add event-log-release

index.yml
Hi!
Quarks team here, can we have https://github.com/cloudfoundry-incubator/quarks-gora-release added to bosh.io? 
Thank you!
=> Add quarks-gora release

index.yml
add the external postgres metrics emmiter to bosh.io/releases from
https://github.com/starkandwayne/external-postgres-metrics-emitter-release
=> add external-postgres-metrics-emmiter

index.yml
HAProxy BOSH release was recently moved from the cloudfoundry-incubator org to cloudfoundry. This change:
* Adds a BOSH release for HAProxy using the path for the new org
* Removes the _very old_ Cloud Foundry community version of HAProxy BOSH Release
* Keeps the cloudfoundry-incubator (I expect this is be necessary so users can access old versions?)
Related discussion in CF Slack https://cloudfoundry.slack.com/archives/C01ABMVNE9E/p1634666203051000
- ✅ LICENSE and NOTICE files are up to date
- ✅ at least one final release is checked in on the default repo branch (there's a `.final_builds` folder)
- ✅ of use to the general community and will be maintained
- ✅ github repo must be public
- ✅ bosh create-release must run successfully against all final releases (the …
=> Add version of HAProxy BOSH release with new org

index.yml
Note: We created this bosh release quite a while ago and successfully use it in production along our Cloud Foundry deployment. However, we never came around to finalise the missing bits and pieces to share it properly.
But here we are, better late than never.
=> Add BOSH release for Varnish

index.yml
The [cflinuxfs4 bosh release](https://github.com/cloudfoundry/cflinuxfs4-release) deploys the [cflinuxfs4 rootfs](https://github.com/cloudfoundry/cflinuxfs4).
=> Add cflinuxfs4 bosh release

index.yml
The [Healthchecker bosh release](https://github.com/cloudfoundry/Healthchecker) is being moved out of [cf-networking-helpers/healthchecker](https://github.com/cloudfoundry/cf-networking-helpers/tree/main/healthchecker) to address dependency conflicts in the future.
=> Add Healthchecker bosh release

index.yml
The [cflinuxfs4 compatibility bosh
release](https://github.com/cloudfoundry/cflinuxfs4-compat-release) deploys the [cflinuxfs4
rootfs](https://github.com/cloudfoundry/cflinuxfs4). The compatibility release includes Ruby and Python as decided in the RFC [Proposal for Ruby and Python Removal from the cflinuxfs4 Stack with a Deprecation
Period](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0016-python-and-ruby-removal-from-cf-stack.md). This depends on https://github.com/cloudfoundry/community/pull/590
=> Add cflinuxfs4 compatibility bosh release

index.yml
prometheus-boshrelease and node-exporter-boshrelease have moved a while ago to bosh-prometheus gh org
See related slack thread https://cloudfoundry.slack.com/archives/C02FL4A2K/p1707488086281179?thread_ts=1707462526.630869&cid=C02FL4A2K
=> Update git url for prometheus-boshrelease and node-exporter-boshrelease

index.yml
prometheus-boshrelease has moved  from bosh-prometheus gh org to cloudfoundry gh org
=> move-prometheus-boshreleas-to-cloudfoundry
