index.yml

Add bpm-release to the list of releases

---

index.yml

Update cf-networking-release to be in cloudfoundry org

---

index.yml

Windows equivalent of os-conf-release.

Add windows-utilities-release

---

index.yml

Add bits-service

---

index.yml

Add CF appication service discovery release

---

index.yml

[#156242645]
Signed-off-by: Caroline Taymor <ctaymor@pivotal.io>

Add pxc-release to boshio

---

avatars.yml

added my github avatar to avatars.yml

added martyca avatar

---

index.yml

We have opensourced these releases

Add mysql-backup-release and mysql-monitoring-release

---

index.yml

Signed-off-by: Andrew Poydence <apoydence@pivotal.io>
@bradylove

Adds cloudfoundry/service-metrics-release

---

index.yml

Adds cflinuxfs3-release.
Signed-off-by: Leah Hanson <lhanson@pivotal.io>

Adds cloudfoundry/cflinuxfs3-release

---

index.yml

Adds new nginx buildpack release to indexed files
[#159444595]

Add nginx-buildpack-release

---

index.yml

Add leadership election release to bosh.io

---

index.yml

[#165985412]
Signed-off-by: Travis Patterson <tpatterson@pivotal.io>

Add service-logs-release to bosh.io

---

index.yml

[#168088295]
Signed-off-by: Caitlyn Yu <cyu@pivotal.io>

add metrics discovery release to bosh.io

---

index.yml

This release collects vm metrics and puts them into the Loggregator system.

Add system metrics release

---

avatars.yml
index.yml

[add] terraboard-boshrelease

---

index.yml

add Orange generic-scripting bosh release.

add scripting release

---

avatars.yml
index.yml

BBR release that allows backing up and restoring any data from VM.

Add Filesystem BBR

---

index.yml

Add listing for new Bosh release of the Datadog Cluster Agent

---

index.yml

add the safe bosh release https://github.com/cloudfoundry-community/safe-boshrelease

add the safe bosh release

---

index.yml

Add otel-collector release

---

index.yml

feat: Add the Loki Bosh release to Bosh.io

---

index.yml

add k3s bosh releases

---

avatars.yml
index.yml

add praeco bosh release
